services:
  sqlserver:
    build:
      context: .
      dockerfile: Dockerfile_sqlserver
    container_name: sqlserver_container
    environment:
      SA_PASSWORD: "YourStrong@Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - etl_network

  etl_pipeline:
    build:
      context: .
      dockerfile: Dockerfile_etl
    container_name: etl_container
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/credentials.json
      - SQL_SERVER_HOST=sqlserver_container
      - SQL_SERVER_PORT=1433
    depends_on:
      - sqlserver
    volumes:
      - ./data:/app/data          # Carpeta local para archivos CSV
      - ./credentials.json:/app/credentials.json
    networks:
      - etl_network

# Declaración de la red
networks:
  etl_network:
    driver: bridge